### ISSUE TITLE
is elechouse NFC V3 HSU supported? (a PN532 device)

### ISSUE THREAD

**Issue by xetum** [nfcpy/nfcpy#104]
python -m nfc --search-tty hangs indefinitely. Should find "tty:S0:pn532". libnfc-derived packages detect device

**Comment by nehpetsde** [comment]
Please post the output of the search.

**Comment by xetum** [comment]
pi@raspberrypi:~ $ python -m nfc --search-tty
This is the 0.13.1 version of nfcpy run in Python 2.7.9
on Linux-4.9.28-v7+-armv7l-with-debian-8.0
I'm now searching your system for contactless devices

(hanged)

**Comment by nehpetsde** [comment]
Is this a Raspberry Pi? If so, can you post the output of  `cat /proc/cpuinfo`.

**Comment by xetum** [comment]
pi@raspberrypi:~ $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a02082
Serial		: 0000000080cbb4c5
pi@raspberrypi:~ $

**Comment by nehpetsde** [comment]
Thanks. The problem is that nfcpy tries to enable fast serial connection with 921.6 kbps which the RPi 3 can't handle on ttyS0. Unfortunately the logic to discover an RPi is based on the BCM270? silicon identifier that used to be in cpuinfo. Apparently this has changed to the BCM283? chip package identifier ([ref](https://raspberrypi.stackexchange.com/questions/840/why-is-the-cpu-sometimes-referred-to-as-bcm2708-sometimes-bcm2835)). I'll try to find a more robust way. Meantime, if you use the nfcpy git source, you can temporarily exchange "BCM270" with "BCM283" in [src/nfc/clf/pn532.py](https://github.com/nfcpy/nfcpy/blob/6ebb26b8f3a47183a66002b05a2c780a7e861b24/src/nfc/clf/pn532.py#L397).

**Comment by xetum** [comment]
Many thanks, it works. I've just recompiled the already installed pn532.py.
Greetings from Barcelona. Freedom for catalan president Puigdemont

**Comment by nehpetsde** [comment]
Solved with release 0.13.5
