### ISSUE TITLE
Supported Devices

### ISSUE THREAD

**Issue by YannikSc** [nfcpy/nfcpy#66]
Is there a list with supported devices? Can/should I trust neard (obviously not, the PN544 is working with neard but not detected by nfc.clf)?

**Comment by nehpetsde** [comment]
The list is here -> https://nfcpy.readthedocs.io/en/latest/overview.html#supported-devices. The PN544 is not supported because it is seems, to my knowledge, not to be used in commercially available reader devices but only integrated in smartphones. If PN544 would become a reader option, it would still first require an nfcpy implementation of the NCI protocol for host-device communication.

**Comment by Cirengg** [comment]
Is there a way to add a new device to the list?
