### ISSUE TITLE
nfcpy with android?

### ISSUE THREAD

**Issue by userDevop123** [nfcpy/nfcpy#83]
can I run nfcpy with android? how please?
with witch reader nfcpy work?

**Comment by nehpetsde** [comment]
You can run nfcpy on a Linux/Windows/Mac computer and exchange data over NFC with any Android phone. But you can not run nfcpy on an Android phone. Theoretically one could manage to run Python on Android and install nfcpy into the Python environment this would still be no use because the NFC chipsets on Android phones are not the same as in consumer reader devices.

**Comment by userDevop123** [comment]
@nehpetsde all the Android phones has the same NFC chipsets ? (witch kind?)
with witch kind of NFC chipsets nfcpy works?  and do you know another project that work on android?

**Comment by andychlee** [comment]
@userDevop123 [This](https://en.wikipedia.org/wiki/List_of_NFC-enabled_mobile_devices) lists android phones with their NFC controllers. And for using NFC on Android, refer to https://developer.android.com/guide/topics/connectivity/nfc/index.html
